spring.application.name=demo
spring.ai.model.chat=google-genai
spring.ai.google.genai.api-key=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
spring.ai.google.genai.chat.model=gemini-3.5-flash
weather.api.key=whether-api-key
